package role

var Permission = map[string]map[string]bool{
	"superadmin": {
		// organization
		"branch.create":            true,
		"branch.read":              true,
		"branch.update":            true,
		"branch.delete":            true,
		"department.create":        true,
		"department.read":          true,
		"department.update":        true,
		"department.delete":        true,
		"position.create":          true,
		"position.read":            true,
		"position.update":          true,
		"position.delete":          true,
		"position_category.create": true,
		"position_category.read":   true,
		"position_category.update": true,
		"position_category.delete": true,
		"employee_type.create":     true,
		"employee_type.read":       true,
		"employee_type.update":     true,
		"employee_type.delete":     true,
		"employee_master.create":   true,
		"employee_master.read":     true,
		"employee_master.delete":   true,
		"employee_mutation.create": true,
	},
	"staff": {
		// organization
		"branch.create":            true,
		"branch.read":              true,
		"branch.update":            true,
		"department.create":        true,
		"department.read":          true,
		"department.update":        true,
		"position.create":          true,
		"position.read":            true,
		"position.update":          true,
		"position_category.create": true,
		"position_category.read":   true,
		"position_category.update": true,
		"employee_type.create":     true,
		"employee_type.read":       true,
		"employee_type.update":     true,
		"employee_master.create":   true,
		"employee_master.read":     true,
		"employee_mutation.create": true,
	},
}
